//
//  ABCStandardView.swift
//  ScoreEdit
//
//  Created by Stephen Beitzel on 9/26/26.
//

import AppKit
import SwiftUI
import WebKit

/// Displays the bundled offline copy of the ABC 2.2 standard
/// (generated by `scripts/generate-abc-standard.py`).
struct ABCStandardView: View {
    @State private var page = WebPage(navigationDecider: ExternalLinkDecider())

    var body: some View {
        WebView(page)
            .task {
                page.load(html: Self.standardHTML)
            }
    }

    private static let standardHTML: String = {
        guard
            let url = Bundle.module.url(forResource: "ABCStandard", withExtension: "html"),
            let html = try? String(contentsOf: url, encoding: .utf8)
        else {
            return "<p>\(String(localized: .kerrAbcStandardUnavailable))</p>"
        }
        return html
    }()
}

/// Keeps in-document navigation (the table of contents and cross references)
/// inside the view, and hands every link to the web off to the default browser.
private struct ExternalLinkDecider: WebPage.NavigationDeciding {
    @MainActor
    func decidePolicy(
        for action: WebPage.NavigationAction,
        preferences: inout WebPage.NavigationPreferences
    ) async -> WKNavigationActionPolicy {
        guard
            action.navigationType == .linkActivated,
            let url = action.request.url,
            url.scheme == "http" || url.scheme == "https"
        else {
            return .allow
        }
        NSWorkspace.shared.open(url)
        return .cancel
    }
}

#Preview {
    ABCStandardView()
}
